baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'HackForge'
theme='hugo-theme-relearn'
relativeURLs = true
[params]
  showRightSidebar = true
  disableHoverBlockCopyToClipBoard=true
  disableCopyToClipBoard = true
  [[params.themeVariant]]
  identifier = 'zen-dark'
